version: '3.5'

services:
    app:
        image: node:10-alpine
        container_name: app
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: 200m
                max-file: '10'
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=production
        networks:
            - app-network
        volumes:
            # adding the compiled sources as volumes allows for zero-downtime reloads
            - ./:/app
            - ../luckyblock-dist:/luckyblock-dist
        command: /bin/sh -c "cd app && npm run start-cluster"

    nginx:
        image: nginx:mainline-alpine
        container_name: nginx
        restart: unless-stopped
        logging:
            driver: json-file
            options:
                max-size: 200m
                max-file: '10'
        depends_on:
            - app
        ports:
            - '80:80'
            - '443:443'
        networks:
            - app-network
        volumes:
            - ./server/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./server/dhparam:/etc/ssl/certs
            - ./client/dist:/var/www/html # only used by certbot
            - ../certbot-etc:/etc/letsencrypt
            - ../certbot-var:/var/lib/letsencrypt

    # this is only needed on the initial deploy and for renewals
    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            # change this to a non-https nginx on the initial deploy
            - nginx
        volumes:
            - ./client/dist:/var/www/html
            - ../certbot-etc:/etc/letsencrypt
            - ../certbot-var:/var/lib/letsencrypt
        command: certonly --webroot --webroot-path=/var/www/html --agree-tos --no-eff-email --force-renewal -d luckyblockmod.com -d www.luckyblockmod.com

networks:
    app-network:
        driver: bridge
