version: '3.5'

services:
    app:
        image: node:10-alpine
        container_name: app
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=production
        networks:
            - app-network
        volumes:
            # adding the compiled sources as volumes allows for zero-downtime reloads
            - ./:/app
            - ../../luckyblock-dist:/luckyblock-dist
        command: /bin/sh -c "cd app && npm run start-cluster"

    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - '80:80'
            - '443:443'
        networks:
            - app-network
        volumes:
            - ./server/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./server/dhparam:/etc/ssl/certs
            - ./client/dist:/var/www/html # only used by certbot
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt

    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            # note: change this to a non-https webserver on the initial deploy
            - webserver
        volumes:
            - ./client/dist:/var/www/html
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        command: certonly --webroot --webroot-path=/var/www/html --agree-tos --no-eff-email --force-renewal -d luckyblockmod.com -d www.luckyblockmod.com

volumes:
    certbot-etc:
    certbot-var:

networks:
    app-network:
        driver: bridge
