version: '3.5'

services:
    app:
        build:
            context: .
            target: run-server
        ports:
            - 8080:8080
        networks:
            - app-network
        volumes:
            - ../luckyblock-dist:/luckyblock-dist

    # use this when testing locally, and on the initial deploy (before certbot enables https)
    nginx:
        image: nginx:mainline-alpine
        depends_on:
            - app
        ports:
            - '80:80'
        networks:
            - app-network
        volumes:
            - ./server/nginx-conf/nginx-http.conf:/etc/nginx/conf.d/default.conf

networks:
    app-network:
        driver: bridge
