version: '3.5'

services:
    app:
        build:
            context: .
            target: luckyblock-website
            dockerfile: Dockerfile
        image: app
        container_name: app
        restart: unless-stopped
        networks:
            - app-network
        volumes:
            - ./src:/app/src
        command: npm run serve

    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./src/pages:/var/www/html
            - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./dhparam:/etc/ssl/certs
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        networks:
            - app-network

    webserver-local:
        image: nginx:mainline-alpine
        container_name: webserver-local
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./src/pages:/var/www/html
            - ./nginx-conf/nginx-local.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./src/static:/var/www/html
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        command: certonly --webroot --webroot-path=/var/www/html --email admin@minecraftascending.com --agree-tos --no-eff-email --staging -d minecraftascending.com -d www.minecraftascending.com

volumes:
    certbot-etc:
    certbot-var:

networks:
    app-network:
        driver: bridge
